"""create almost all tables

Revision ID: 38fff8d2d5c7
Revises: 92a04164c149
Create Date: 2026-06-21 15:06:28.672946

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "38fff8d2d5c7"
down_revision: Union[str, Sequence[str], None] = "92a04164c149"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sticker_packs",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_premium", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "dialogs",
        sa.Column("user1_id", sa.Uuid(), nullable=False),
        sa.Column("user2_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user1_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user2_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("user1_id", "user2_id", name="unique_dialog_pair"),
        sa.UniqueConstraint("user2_id", "user1_id", name="unique_dialog_pair_reverse"),
    )
    op.create_table(
        "groups",
        sa.Column("title", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "stickers",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("file_url", sa.String(), nullable=False),
        sa.Column("emoji", sa.String(length=5), nullable=False),
        sa.Column("pack_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["pack_id"], ["sticker_packs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "user_contacts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("contact_user_id", sa.Uuid(), nullable=False),
        sa.Column("custom_name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["contact_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("user_id", "contact_user_id", name="unique_user_contact"),
    )
    op.create_table(
        "group_members",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "MEMBER", name="roles_member_groups"),
            nullable=False,
        ),
        sa.Column(
            "joined_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id", "user_id"),
        sa.UniqueConstraint("group_id", "user_id", name="unique_group_user"),
    )
    op.create_table(
        "messages",
        sa.Column("sender_id", sa.Uuid(), nullable=True),
        sa.Column("dialog_id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "TEXT",
                "IMAGE",
                "VOICE",
                "STICKER",
                "FILE",
                "SYSTEM",
                name="message_types",
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("file_url", sa.String(), nullable=True),
        sa.Column("sticker_id", sa.Uuid(), nullable=False),
        sa.Column("reply_to_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("is_edited", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(type = 'SYSTEM' AND sender_id IS NULL) OR (type != 'SYSTEM' AND sender_id IS NOT NULL)",
            name="system_message_check",
        ),
        sa.CheckConstraint(
            "type != 'STICKER' OR sticker_id IS NOT NULL", name="sticker_required"
        ),
        sa.CheckConstraint(
            "type NOT IN ('IMAGE', 'VOICE', 'FILE') OR file_url IS NOT NULL",
            name="file_url_required",
        ),
        sa.CheckConstraint(
            "(dialog_id IS NOT NULL AND group_id IS NULL) OR (dialog_id IS NULL AND group_id IS NOT NULL)",
            name="message_target_check",
        ),
        sa.ForeignKeyConstraint(["dialog_id"], ["dialogs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reply_to_id"], ["messages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["sender_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["sticker_id"], ["stickers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "message_statuses",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("message_id", "user_id"),
        sa.UniqueConstraint("message_id", "user_id", name="unique_message_status"),
    )
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_table("message_statuses")
    op.drop_table("messages")
    op.drop_table("group_members")
    op.drop_table("user_contacts")
    op.drop_table("stickers")
    op.drop_table("groups")
    op.drop_table("dialogs")
    op.drop_table("sticker_packs")
    # ### end Alembic commands ###
