"""create columns for last messages

Revision ID: 43115e66b099
Revises: 38fff8d2d5c7
Create Date: 2026-06-21 16:11:00.108211

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "43115e66b099"
down_revision: Union[str, Sequence[str], None] = "38fff8d2d5c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dialogs", sa.Column("last_message_id", sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, "dialogs", ["id"])
    op.create_foreign_key(
        None, "dialogs", "messages", ["last_message_id"], ["id"], ondelete="SET NULL"
    )
    # op.create_unique_constraint(
    #     "unique_group_user", "group_members", ["group_id", "user_id"]
    # )
    op.add_column("groups", sa.Column("last_message_id", sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, "groups", ["id"])
    op.create_foreign_key(
        None, "groups", "messages", ["last_message_id"], ["id"], ondelete="SET NULL"
    )
    # op.create_unique_constraint(
    #     "unique_message_status", "message_statuses", ["message_id", "user_id"]
    # )
    op.create_unique_constraint(None, "messages", ["id"])
    op.create_unique_constraint(None, "sticker_packs", ["id"])
    op.create_unique_constraint(None, "stickers", ["id"])
    op.create_unique_constraint(None, "user_contacts", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_contacts", type_="unique")
    op.drop_constraint(None, "stickers", type_="unique")
    op.drop_constraint(None, "sticker_packs", type_="unique")
    op.drop_constraint(None, "messages", type_="unique")
    op.drop_constraint("unique_message_status", "message_statuses", type_="unique")
    op.drop_constraint(None, "groups", type_="foreignkey")
    op.drop_constraint(None, "groups", type_="unique")
    op.drop_column("groups", "last_message_id")
    op.drop_constraint("unique_group_user", "group_members", type_="unique")
    op.drop_constraint(None, "dialogs", type_="foreignkey")
    op.drop_constraint(None, "dialogs", type_="unique")
    op.drop_column("dialogs", "last_message_id")
    # ### end Alembic commands ###
