"""adding indexes

Revision ID: f9f93d08a75a
Revises: 43115e66b099
Create Date: 2026-06-21 17:31:12.446079

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f9f93d08a75a"
down_revision: Union[str, Sequence[str], None] = "43115e66b099"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_message_statuses_is_read"),
        "message_statuses",
        ["is_read"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_statuses_message_id"),
        "message_statuses",
        ["message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_statuses_user_id"),
        "message_statuses",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_messages_created_at"), "messages", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_messages_dialog_id"), "messages", ["dialog_id"], unique=False
    )
    op.create_index(op.f("ix_messages_group_id"), "messages", ["group_id"], unique=False)
    op.create_index(
        op.f("ix_messages_is_deleted"), "messages", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_messages_sender_id"), "messages", ["sender_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_sender_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_is_deleted"), table_name="messages")
    op.drop_index(op.f("ix_messages_group_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_dialog_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_created_at"), table_name="messages")
    op.drop_index(op.f("ix_message_statuses_user_id"), table_name="message_statuses")
    op.drop_index(op.f("ix_message_statuses_message_id"), table_name="message_statuses")
    op.drop_index(op.f("ix_message_statuses_is_read"), table_name="message_statuses")
    # ### end Alembic commands ###
